import Header from '@/components/Header'
import MobileNav from '@/components/MobileNav'
import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head';
import { useState } from 'react';

import { AnimatePresence } from "framer-motion"

import asPath from "next/router"


export default function App({ Component, pageProps, router }: AppProps) {

  const [navMobile, setNavMobile] = useState<boolean>(false);


  return (
    <>
      <Head>
        <title>Samuel NDJOULI AMOUGOU | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

      </Head>
      <Header setNavMobile={setNavMobile} />
      <div className={`${navMobile ? 'right-0' : '-right-full'} fixed z-10 top-0 h-full transition-all duration-200`}>
        <MobileNav setNavMobile={setNavMobile} />
      </div>
      <AnimatePresence
        initial={true}
        mode="wait"
      >
        <Component {...pageProps} key={router.route} />
      </AnimatePresence>

    </>
  )
}
